### PR TITLE
Marking methods of EmailService that implement IEmailService as virtual.

### PR DESCRIPTION
**Pull request by paracycle**
This is another quick one.

I wanted to replace the SmtpClient implementation with Amazon SES and tried to subclass from `EmailService` so as to not write the `CreateMailMessage` method again. That meant that I had to mark my `Send` and `SendAsync` methods as `new`. It turns out, however, that these `new`methods are not called if one uses the `IEmailService` interface to call methods. I had to find that out the hard way. :)

So the change marks methods of `EmailService` that implement `IEmailService` as virtual so that library consumers can subclass `EmailService` to make minor modifications by overriding stock methods.

### CODE REVIEW

**Comment by andrewdavey** [comment]
Thanks for the pull request. There's a good chance I'll merge it. I'm still
thinking through the options, since I'm usually cautious about making
everything virtual.
Ideally your Amazon SES email service implementation shouldn't subclass
EmailService. I may instead move the CreateMailMessage implementation out
into a public helper class.
I'll let you know.

**Comment by paracycle** [comment]
Actually that's a much better idea. Mine was a quick fix to sort my own problem out without re-architecting the project.

I also had a queasy feeling about the `CreateMailMessage` method being a part of `IEmailService` since it violates the Single Responsibility Principle. `IEmailService` should be an interface that is only responsible for sending email (sync and async).

**Comment by andrewdavey** [comment]
I'm sorry for letting this hang here for so long! If others are also trying to implement `IEmailService`, I think the simplest solution for now is to directly copy `CreateEmailMessage` from `EmailService`. So don't subclass `EmailService`, just implement the `IEmailService` interface.

**Comment by route2Dev** [comment]
I was looking to override only the CreateEmailMessage to inject a "Test" email address for our lower environments and then re-use the other methods of the EmailService to send the email. Having the CreateEmailMessage method be virtual would be very helpful in this endeavor. Otherwise we would end up copying the entire EmailService class just to override this one method and add 4 lines of code.

Please reconsider making the CreateEmailMessage method virtual.

**Pull request closed without merging**
