### PR TITLE
update dependencies, target .NET 4.5, MVC 5.1

### PR DESCRIPTION
**Pull request by tomgallard**
Wanted to use Postal with MVC 5.1, but was coming across multiple errors

### CODE REVIEW

**Comment by dotnetchris** [comment]
Andrew an update for this really needs done. this looks like it would temporarily fix the problem but as far as i can see in there it doesn't address the underlying issue. The hard dependencies to versions, i think it really needs a nuspec file that just sets minimum versions instead not explicit versions.

I see the nuspec exists https://github.com/andrewdavey/postal/blob/master/build/Postal.nuspec but it only defines 1 dependency which is MVC3, should it have additional dependencies listed there? It seems like there should be a dependency in the nuspec for RazorEngine additionally.

**Comment by earaya** [comment]
@andrewdavey: it would be great to merge this. postal is the only reason i haven't been able to upgrade one of my projects to mvc5.

thanks!

**Comment by miketrionfo** [comment]
@andrewdavey I agree with the previous comments.  This looks to be a very good project but I am not able to use it because I'm in MVC 5.  Merging this pull request would be a great step forward.

**Comment by andrewdavey** [comment]
Thanks @tomgallard . I've published an updated nuget package `v0.9.2`.

@dotnetchris as far as I can tell the nuspec only specifies MVC 3.0 and higher. Am I misunderstanding?

**Comment by AKlaus** [comment]
Hi @andrewdavey,

Just tested your last `v0.9.2` and it still doesn't work if I target `MVC 5.0`. See an error below:

```
Error   594 Assembly 'Postal, Version=0.9.2.0, ... uses 'System.Web.Mvc, Version=5.1.0.0, which has a higher version than referenced assembly 'System.Web.Mvc, Version=5.0.0.0
```

Is there anything what I can do to make it work?

**Comment by andrewdavey** [comment]
What assembly binding redirects do you have in web.config?

**Comment by AKlaus** [comment]
Please find them below:

```
      <dependentAssembly>
        <assemblyIdentity name="System.Web.Helpers" publicKeyToken="31bf3856ad364e35" />
        <bindingRedirect oldVersion="1.0.0.0-3.0.0.0" newVersion="3.0.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Web.Mvc" publicKeyToken="31bf3856ad364e35" />
        <bindingRedirect oldVersion="0.0.0.0-5.0.0.0" newVersion="5.0.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Web.WebPages" publicKeyToken="31bf3856ad364e35" />
        <bindingRedirect oldVersion="1.0.0.0-3.0.0.0" newVersion="3.0.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="WebGrease" publicKeyToken="31bf3856ad364e35" />
        <bindingRedirect oldVersion="0.0.0.0-1.5.2.14234" newVersion="1.5.2.14234" />
      </dependentAssembly>
```

I got the Postal through the `NuGet` and checked dependencies of `Postal.dll` in the `packages` folder. It does have a reference to Mvc 5.1

**Comment by andrewdavey** [comment]
Are we going to have to create different builds of Postal for each version of MVC?!

**Comment by dotnetchris** [comment]
Is it possible that Postal could be reduced down to only depending on http://www.nuget.org/packages/Microsoft.AspNet.Razor/ ? or razorengine ?

**Comment by andrewdavey** [comment]
I only use Razor myself, but it seems a shame to drop support for all other view engines just to avoid the MVC dependency.

**Pull request merged**
