### PR TITLE
Upgrades to address the new RazorEngine version

### PR DESCRIPTION
**Pull request by TylerBrinks**
Updated the NuGet refs to RazorEngine 3.0.5, Fixed the file view engine's static constructor reflection query to find the generic Parse method with 3 args.

### CODE REVIEW

**Comment by andrewdavey** [comment]
I took this opportunity to clean up some other parts of the repo. So I couldn't cleanly merge your branch. Thanks for motivating me though! Postal 0.7.0 is now in nuget and depends on RazorEngine 3.0

**Comment by Antaris** [comment]
I've just pushed v3.0.6beta of RazorEngine to Nuget, small bug fix, but also added in support for the missing non-generic Parse methods.

**Comment by andrewdavey** [comment]
@Antaris 
Thanks for the update.
I'm using RazorEngine's `Compile` and `Run` methods here: https://github.com/andrewdavey/postal/blob/master/src/Postal/FileSystemRazorView.cs#L22

Is there a better way with the new API? `Render` currently calls `Razor.Compile` each time. Is this a problem?

**Comment by Antaris** [comment]
Not really a problem, although you can wrap up both calls with `Parse`, as internally the parse method (with a name argument), will check the cache first, and if there is a cached template (with the same source hashcode), it will use the cached template type instead of compiling. E.g, change your calls to:

```
string content = Razor.Parse(template, viewContext.ViewData.Model, cacheName);
```

If the content of the template had changed (i.e., is different then what was used to compile the original template - determined by the hashcode), it will be recompiled to ensure that the newest template version is used for that cache name.

**Comment by Antaris** [comment]
You might want to simplify the cache name now, by ignoring the last file write time. Because of the recompilation mechanism, you no longer need a unique name for each compile, it will determine it for you :-)

**Comment by andrewdavey** [comment]
Awesome, thanks. I've pushed those changes to master.

**Comment by Antaris** [comment]
Cool, I'd recommend making the same change to the your `ResourceRazorView` too?

**Pull request closed without merging**
